CREATE TABLE CHUONGTRINHHOC(
ID	CHAR(50) NOT NULL,
SACHHOC VARCHAR(15) NOT NULL,
UNIT INT NOT NULL,
SOBUOI INT NOT NULL,
CONSTRAINT CTH PRIMARY KEY(ID)
);

CREATE TABLE CHINHANH(
ID	CHAR(50) NOT NULL,
DIACHI VARCHAR(50) NOT NULL,
MOTACHINHANH TEXT,
TENCHINHANH VARCHAR(20) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE KHOAHOC(
ID	CHAR(50) NOT NULL,
TENKHOA VARCHAR(20) NOT NULL,
YEUCAUDAUVAO VARCHAR(5) NOT NULL,
HOCPHI INT NOT NULL,
NGAYBATDAU DATE,
NGAYKETTHUC DATE,
PRIMARY KEY (ID)
);

CREATE TABLE LOPHOC(
ID	CHAR(50) NOT NULL,
TENLOP VARCHAR(50) NOT NULL,
IDKHOAHOC CHAR(50) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE BUOIHOC(
ID	CHAR(50) NOT NULL,
NOIDUNGDAY TEXT,
NGAYTHANGNAM DATE,
IDLOPHOC CHAR(50) NOT NULL,
IDCHUONGTRINH CHAR(50) NOT NULL,
PRIMARY KEY (ID)


);

CREATE TABLE KHUYENMAI(
ID CHAR(50) NOT NULL,
NGAYBATDAU DATE,
NGAYKETTHUC DATE,
PRIMARY KEY (ID)
);

CREATE TABLE HOADON(
ID CHAR(50) NOT NULL,
PHUONGTHUC VARCHAR(25) NOT NULL,
THOIGIAN DATE NOT NULL,
TRANGTHAI VARCHAR(20),
IDKHOAHOC CHAR(50) NOT NULL,
IDHOCVIEN CHAR(50) NOT NULL,
IDTHUNGAN CHAR(50),
GIATIEN int,
PRIMARY KEY (ID)
);
-- create database btl;
CREATE TABLE HOCVIEN(
ID CHAR(50) NOT NULL,
TEN VARCHAR(30) NOT NULL,
SDT CHAR(10) ,
DIACHI VARCHAR(50),
MAIL VARCHAR(30),
NAMSINH DATE,
TRINHDODAUVAO VARCHAR(5),
TENDANGNHAP VARCHAR(30) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE PHUHUYNH(
CMND CHAR(12) NOT NULL,
TEN VARCHAR(30),
DIACHI VARCHAR(30),
MAIL VARCHAR(30),
TENDANGNHAP VARCHAR(30),
PRIMARY KEY(CMND)


);
CREATE TABLE SDT(
CMND CHAR(12) NOT NULL,
SDT CHAR(10) NOT NULL,
PRIMARY KEY (CMND,SDT)
);

CREATE TABLE VOUCHER(
IDKHUYENMAI CHAR(50) NOT NULL,
MAVOUCHER CHAR(50),
LOAIGIAM varchar(5) NOT NULL,
GIATRI int,
GIAMTOIDATHEOPHANTRAM INT,
PRIMARY KEY(IDKHUYENMAI)
);

CREATE TABLE QUATANG(
IDKHUYENMAI CHAR(50),
TENQUATANG VARCHAR(255),
GIATRIQUATANG INT,
SOLUONG INT,
PRIMARY KEY(IDKHUYENMAI)
);

CREATE TABLE NHANVIEN(
ID CHAR(50) NOT NULL,
TEN VARCHAR(30) NOT NULL,
SDT CHAR(10) NOT NULL,
LUONG INT,
DIACHI VARCHAR(50),
MAIL VARCHAR(50) NOT NULL,
IDCHINHANH CHAR(50) NOT NULL,
TENDANGNHAP VARCHAR(30) NOT NULL,
NGAYSINH date not null,
PRIMARY KEY (ID)
);

CREATE TABLE THUNGAN(
IDNHANVIEN CHAR(50) NOT NULL,
PRIMARY KEY(IDNHANVIEN),
CONSTRAINT fk_thungan_nv FOREIGN KEY(IDNHANVIEN) REFERENCES NHANVIEN(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE NGUOIGIANGDAY(
IDNHANVIEN CHAR(50) NOT NULL,
PRIMARY KEY(IDNHANVIEN),
CONSTRAINT fk_nguoigiangday_nv FOREIGN KEY(IDNHANVIEN) REFERENCES NHANVIEN(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE GIANGVIEN(
IDNHANVIEN CHAR(50) NOT NULL,
BANGCAP VARCHAR(255),
KINHNGHIEM TEXT,
PRIMARY KEY(IDNHANVIEN),
CONSTRAINT fk_giangvien_ngd FOREIGN KEY(IDNHANVIEN) REFERENCES NGUOIGIANGDAY(IDNHANVIEN)
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TA(
IDNHANVIEN CHAR(50) NOT NULL,
PRIMARY KEY(IDNHANVIEN),
CONSTRAINT fk_ta_ngd FOREIGN KEY(IDNHANVIEN) REFERENCES NGUOIGIANGDAY(IDNHANVIEN)
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TAIKHOAN(
TENDANGNHAP VARCHAR(30) NOT NULL,
MATKHAU VARCHAR(20) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PRIMARY KEY(TENDANGNHAP)

);

CREATE TABLE QUANLY(
IDNHANVIEN CHAR(50) NOT NULL,
IDQUANLY CHAR(50) NOT NULL,
PRIMARY KEY (IDNHANVIEN),
CONSTRAINT fk_quanly_nv1 FOREIGN KEY(IDNHANVIEN) REFERENCES NHANVIEN(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_quanly_nv2 FOREIGN KEY(IDQUANLY) REFERENCES NHANVIEN(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE KHOAHOC_CTH(
IDCHUONGTRINH CHAR(50) NOT NULL,
IDKHOAHOC CHAR(50) NOT NULL,
NOIDUNGDAY TEXT,
PRIMARY KEY (IDCHUONGTRINH,IDKHOAHOC),
CONSTRAINT fk_khoahoc_cth_cth FOREIGN KEY(IDCHUONGTRINH) REFERENCES CHUONGTRINHHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_khoahoc_cth_kh FOREIGN KEY(IDKHOAHOC) REFERENCES KHOAHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE PHONGHOC(
IDCHINHANH CHAR(50) NOT NULL,
SOPHONG VARCHAR(5) NOT NULL,
SUCCHUA VARCHAR(200) ,
PRIMARY KEY (IDCHINHANH,SOPHONG),
CONSTRAINT fk_phonghoc_cn FOREIGN KEY(IDCHINHANH) REFERENCES CHINHANH(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE CHINHANH_KHOAHOC(
IDCHINHANH CHAR(50) NOT NULL,
IDKHOAHOC CHAR(50) NOT NULL,
PRIMARY KEY(IDCHINHANH, IDKHOAHOC),
CONSTRAINT fk_chinhanh_kh_cn FOREIGN KEY(IDCHINHANH) REFERENCES CHINHANH(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_chinhanh_kh_kh FOREIGN KEY(IDKHOAHOC) REFERENCES KHOAHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE BUOIHOC_PHONGHOC(
IDCHINHANH CHAR(50) NOT NULL,
SOPHONG VARCHAR(5) NOT NULL,
IDBUOIHOC CHAR(50) NOT NULL,
PRIMARY KEY(IDCHINHANH,SOPHONG, IDBUOIHOC),
CONSTRAINT fk_buoihoc_ph_ph1 foreign key(IDCHINHANH,SOPHONG) REFERENCES PHONGHOC(IDCHINHANH,SOPHONG)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_buoihoc_ph_bh FOREIGN KEY(IDBUOIHOC) REFERENCES BUOIHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);



CREATE TABLE KHUYENMAI_HOADON(
IDKHUYENMAI CHAR(50) NOT NULL,
IDHOADON CHAR(50) NOT NULL,
PRIMARY KEY (IDHOADON),
CONSTRAINT fk_khuyenmai_hd_km FOREIGN KEY(IDKHUYENMAI) REFERENCES KHUYENMAI(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_khuyenmai_kh_kh1 FOREIGN KEY(IDHOADON) REFERENCES HOADON(ID)
ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE DIEMDANH(
IDBUOIHOC CHAR(50) NOT NULL,
IDHOCVIEN CHAR(50) NOT NULL,
YESNO VARCHAR(3) NOT NULL,
PRIMARY KEY (IDBUOIHOC,IDHOCVIEN),
CONSTRAINT fk_diemdanh_kh FOREIGN KEY(IDBUOIHOC) REFERENCES BUOIHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_diemdanh_hv FOREIGN KEY(IDHOCVIEN) REFERENCES HOCVIEN(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE HOCVIEN_LOPHOC(
IDLOPHOC CHAR(50) NOT NULL,
IDHOCVIEN CHAR(50) NOT NULL,
DIEMKIEMTRA VARCHAR(3),
DIEMTHI VARCHAR(3),
PRIMARY KEY (IDLOPHOC, IDHOCVIEN),
CONSTRAINT fk_hocvien_lh_ld FOREIGN KEY(IDLOPHOC) REFERENCES LOPHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_hocvien_lh_hv FOREIGN KEY(IDHOCVIEN) REFERENCES HOCVIEN(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE DAYHOC(
IDNHANVIEN CHAR(50) NOT NULL,
IDLOPHOC CHAR(50) NOT NULL,
PRIMARY KEY (IDNHANVIEN, IDLOPHOC),
CONSTRAINT fk_dayhoc_ngd FOREIGN KEY(IDNHANVIEN) REFERENCES NGUOIGIANGDAY(IDNHANVIEN)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_dayhoc_lh FOREIGN KEY(IDLOPHOC) REFERENCES LOPHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE HOCSINH_PHUHUYNH(
CMND CHAR(12) NOT NULL,
IDHOCVIEN CHAR(50) NOT NULL,
PRIMARY KEY(IDHOCVIEN),
CONSTRAINT fk_hocsinh_ph_ph FOREIGN KEY(CMND) REFERENCES PHUHUYNH(CMND)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_hocsinh_ph_hv FOREIGN KEY(IDHOCVIEN) REFERENCES HOCVIEN(ID)
ON UPDATE CASCADE ON DELETE CASCADE


);

CREATE TABLE DANHGIA(
TENDNHS VARCHAR(20) NOT NULL,
IDKHOAHOC CHAR(50) NOT NULL,
LOIDANHGIA TEXT,
SOSAO CHAR(1),
PRIMARY KEY(TENDNHS,IDKHOAHOC),
CONSTRAINT fk_danhgia_kh FOREIGN KEY(IDKHOAHOC) REFERENCES KHOAHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE TKB(
ID_LOPHOC CHAR(50) NOT NULL,
THU VARCHAR(10) NOT NULL,
GIO_BDAU TIME NOT NULL,
GIO_KTHUC TIME NOT NULL,
PRIMARY KEY (ID_LOPHOC, THU),
CONSTRAINT fk_tkb_lh FOREIGN KEY(ID_LOPHOC) REFERENCES LOPHOC(ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE LOPHOC ADD CONSTRAINT fk_lophoc_kh3 FOREIGN KEY(IDKHOAHOC) REFERENCES KHOAHOC(ID) ON UPDATE CASCADE ON DELETE CASCADE;


-- BUOIHOC
ALTER TABLE BUOIHOC ADD CONSTRAINT fk_buoihoc_lh1 FOREIGN KEY(IDLOPHOC) REFERENCES LOPHOC(ID) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE BUOIHOC ADD CONSTRAINT fk_buoihoc_ct3 FOREIGN KEY(IDCHUONGTRINH) REFERENCES CHUONGTRINHHOC(ID) ON UPDATE CASCADE ON DELETE CASCADE;



-- HOADON
ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_kh5 FOREIGN KEY(IDKHOAHOC) REFERENCES KHOAHOC(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_hv5 FOREIGN KEY(IDHOCVIEN) REFERENCES HOCVIEN(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_tn5 FOREIGN KEY(IDTHUNGAN) REFERENCES THUNGAN(IDNHANVIEN) ON UPDATE CASCADE ON DELETE CASCADE;


-- HOCVIEN

ALTER TABLE HOCVIEN ADD CONSTRAINT fk_hocvien_tk FOREIGN KEY(TENDANGNHAP) REFERENCES TAIKHOAN(TENDANGNHAP) ON UPDATE CASCADE ON DELETE CASCADE;


-- PHUHUYNH

ALTER TABLE PHUHUYNH ADD CONSTRAINT fk_phuhuynh_tk FOREIGN KEY(TENDANGNHAP) REFERENCES TAIKHOAN(TENDANGNHAP) ON UPDATE CASCADE ON DELETE CASCADE;


-- SDT
ALTER TABLE SDT ADD CONSTRAINT fk_sdt_ph FOREIGN KEY(CMND) REFERENCES PHUHUYNH(CMND) ON UPDATE CASCADE ON DELETE CASCADE;


-- VOUCHER
ALTER TABLE VOUCHER ADD CONSTRAINT fk_voucher_km FOREIGN KEY(IDKHUYENMAI) REFERENCES KHUYENMAI(ID) ON UPDATE CASCADE ON DELETE CASCADE;


-- QUATANG

ALTER TABLE QUATANG ADD CONSTRAINT fk_quatang_km FOREIGN KEY(IDKHUYENMAI) REFERENCES KHUYENMAI(ID) ON UPDATE CASCADE ON DELETE CASCADE;


-- NHANVIEN

ALTER TABLE NHANVIEN ADD CONSTRAINT fk_nhanvien_cn FOREIGN KEY(IDCHINHANH) REFERENCES CHINHANH(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE NHANVIEN ADD CONSTRAINT fk_nhanvien_tk FOREIGN KEY (TENDANGNHAP) REFERENCES TAIKHOAN(TENDANGNHAP) ON UPDATE CASCADE ON DELETE CASCADE;

 







